version: 2
models:
  - name: dim_listings_cleaned
  
    columns:
      - name: listing_id
        tests:
          - unique
          - not_null
      - name: host_id
        tests:
          - relationships:
              to: ref('dim_hosts_cleaned')
              field: host_id
          - not_null
            
